# Generated by Django 4.1.1 on 2022-10-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_alter_cartitem_created_at_alter_cartitem_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price_ht',
            new_name='price',
        ),
    ]
