# Generated by Django 4.1.1 on 2022-10-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_alter_cartitem_tax_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
