# Generated by Django 4.1.1 on 2022-09-28 15:25

import category.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.IntegerField(default=category.utils.create_new_category_code_number, unique=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
