# Generated by Django 4.1.1 on 2022-10-20 09:26

import category.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_managers_category_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(default=category.utils.create_new_category_code_number, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
