# Generated by Django 4.1.1 on 2022-10-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_code_alter_category_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedcategory',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
