# Generated by Django 4.1.1 on 2022-12-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_category_created_by_alter_category_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'name')},
        ),
    ]
