# Generated by Django 4.1.1 on 2022-09-28 15:25

import config.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measureunit',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='code',
            field=models.CharField(default=config.utils.create_new_time_unit_code_number, max_length=5, unique=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
