# Generated by Django 4.1.1 on 2022-09-29 10:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_measureunit_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonConfig',
        ),
        migrations.AlterModelManagers(
            name='azcity',
            managers=[
                ('buyer_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='azcountry',
            managers=[
                ('buyer_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='azpackage',
            managers=[
                ('buyer_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='azstate',
            managers=[
                ('buyer_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='measureunit',
            managers=[
                ('buyer_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='timeunit',
            managers=[
                ('buyer_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='azpackage',
            name='user_type',
            field=models.CharField(choices=[('seller', 'seller'), ('buyer', 'buyer')], default='seller', max_length=6),
        ),
        migrations.AddField(
            model_name='measureunit',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeunit',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='azcity',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='azcountry',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='azpackage',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='azpackage',
            name='package_code',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='azpackage',
            name='package_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='azstate',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
