# Generated by Django 4.1.1 on 2022-09-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_delete_commonconfig_alter_azcity_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azcity',
            name='city_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='azcity',
            name='city_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='azcountry',
            name='country_code',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='azcountry',
            name='country_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='azstate',
            name='state_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='azstate',
            name='state_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='unit',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='unit',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
