# Generated by Django 4.1.1 on 2022-09-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_azcity_city_code_alter_azcity_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeunit',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
