# Generated by Django 4.1.1 on 2022-09-30 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_timeunit_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('code', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Types of Authorization',
                'ordering': ['-created_by'],
            },
        ),
        migrations.AlterModelManagers(
            name='azcity',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='azcountry',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='azpackage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='azstate',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='measureunit',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='timeunit',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_authorization_type', to='config.authorizationtype')),
            ],
            options={
                'verbose_name_plural': 'Time Units',
                'ordering': ['-created_by'],
            },
        ),
    ]
