# Generated by Django 4.1.1 on 2022-10-18 11:49

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=120), unique_with=('name',))),
                ('logo', models.ImageField(upload_to=shop.models.store_upload_to)),
                ('is_active', models.BooleanField(default=False)),
                ('domains', models.ManyToManyField(to='shop.domain')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='StoreManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domains', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.domain')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_manager_role', to='auth.group')),
                ('store', models.ManyToManyField(to='shop.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Manager',
                'verbose_name_plural': 'Store Managers',
            },
        ),
    ]
