# Generated by Django 4.1.1 on 2022-10-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_store_owner_alter_domain_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
