# Generated by Django 4.1.1 on 2022-10-26 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='address_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='address_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
