# Generated by Django 4.1.1 on 2022-10-27 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0003_alter_address_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[(1, 'Default'), (2, 'Cancel'), (3, 'Refund'), (4, 'Success'), (5, 'Processing'), (6, 'Shipped'), (7, 'Done')], default=1, max_length=3)),
                ('delivery_personnel', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
