# Generated by Django 4.1.1 on 2022-10-27 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_options_alter_order_order_status'),
        ('shipping', '0004_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='order',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
