# Generated by Django 4.1.1 on 2022-10-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_options_alter_order_order_status'),
        ('shipping', '0005_shipping_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[(1, 'Default'), (2, 'Cancel'), (3, 'Refund'), (4, 'Success'), (5, 'Processing'), (6, 'Shipped'), (7, 'Done')], default='DEFAULT', max_length=3),
        ),
    ]
