# Generated by Django 4.1.1 on 2022-10-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0009_alter_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Default'), (2, 'Cancel'), (3, 'Refund'), (4, 'Success'), (5, 'Processing'), (6, 'Shipped'), (7, 'Done')], default=1),
        ),
    ]
