# Generated by Django 4.1.1 on 2022-10-26 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_alter_productmedia_created_by_and_more'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(blank=True, default=0)),
                ('order_status', models.CharField(choices=[(1, 'Default')], default=1, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('TAX_AMOUNT', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(default='', max_length=200)),
                ('order_paid_status', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(default='', max_length=200)),
                ('delete', models.BooleanField(default=False)),
                ('address', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='shipping.address')),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='order_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('updated_by', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='order_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
