# Generated by Django 4.1.1 on 2022-10-26 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_alter_order_created_by_alter_order_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
