# Generated by Django 4.1.1 on 2022-10-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_alter_address_updated_by'),
        ('orders', '0003_alter_order_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null='', on_delete=django.db.models.deletion.PROTECT, to='shipping.address'),
        ),
    ]
