# Generated by Django 4.1.1 on 2022-10-21 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availability',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shop_item',
            new_name='store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active_by_seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='validate_by_admin',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='is_active_by_seller',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='validate_by_admin',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='is_active_by_seller',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='validate_by_admin',
        ),
        migrations.AddField(
            model_name='product',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productprice',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productprice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='3'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
