# Generated by Django 4.1.1 on 2022-10-21 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_rename_availability_product_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="The position '1' means is the first image(default to display), basically all other have the position '0'"),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='p_price_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='is_active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_price_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
