# Generated by Django 4.1.1 on 2023-07-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
