# Generated by Django 4.1.1 on 2023-07-30 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_alter_productprice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_price_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
