# Generated by Django 4.1.1 on 2023-08-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='total_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
